name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: keycloak-webhook-listener
          path: target/*.jar

  # Comment the release workflow for now, as we lack the permissions to create a release on GitHub
  # release:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download JAR artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: keycloak-webhook-listener

  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: v1.0.${{ github.run_number }}
  #         release_name: Release v1.0.${{ github.run_number }}
  #         draft: false
  #         prerelease: false

  #     - name: Upload JAR to Release
  #       uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ steps.create_release.outputs.upload_url }}
  #         asset_path: target/*.jar
  #         asset_name: keycloak-webhook-listener.jar
  #         asset_content_type: application/java-archive
